version: "3"

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    # networks:
    #   - mynetwork

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'laravel_test'
      MYSQL_USER: 'test_user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./my-db:/var/lib/mysql
    # networks:
    #   - mynetwork

# networks:
  # default:
    # external:
      # true